// export const assetUrl = "https://dubaievisaservice.com/assets/"
export const assetUrl = "http://127.0.0.1:8001/assets/"
export const genders = [
    {id: 1, name: "Male"},
    {id: 2, name: "Female"},
    {id: 3, name: "Others"}
];

export const bloodGroups = [
    {id: "A+", name: "A+"},
    {id: "A-", name: "A-"},
    {id: "B+", name: "B+"},
    {id: "B-", name: "B-"},
    {id: "AB+", name: "AB+"},
    {id: "AB-", name: "AB-"},
    {id: "O+", name: "O+"},
    {id: "O-", name: "O-"}
];

export const groups = [
    {id: 1, name: "Main Person"},
    {id: 2, name: "Son Of Main Person"},
    {id: 3, name: "Daughter Of Main Person"},
    {id: 4, name: "Wife Of Main Person"}
];
export const jobTypes = [
    {id: 1, name: "Full Time"},
    {id: 2, name: "Part Time"}
];

export const maritalStatuses = [
    {id: 1, name: "Single"},
    {id: 2, name: "Married"},
    {id: 3, name: "Divorced"}
];

export const visaProcessingTypes = [
    {id: 1, name: "Normal"},
    {id: 2, name: "Urgent"},
    {id: 3, name: "A2A"},
    {id: 4, name: "Renewal"}
];

export const visaStatuses = [
    {id: 1, name: "Pending"},
    {id: 2, name: "Processing"},
    {id: 3, name: "Approved"},
    {id: 4, name: "Reject"}
];

export const visaTypesApply = [
    {id: 1, name: "VISIT VISA"},
    {id: 2, name: "EMPLOYMENT VISA"},
    {id: 3, name: "INVESTOR / PARTNER VISA"},
    {id: 4, name: "DOMESTIC WORKER"},
    {id: 5, name: "FREE ZONE / FREELANCER"},
    {id: 6, name: "FAMILY VISA"},
    {id: 7, name: "STUDENT VISA"},
];

export const visaTypes = [
    {id: 1, name: "VISIT VISA"},
    {id: 2, name: "EMPLOYMENT VISA"},
    {id: 3, name: "INVESTOR / PARTNER VISA"},
    {id: 4, name: "DOMESTIC WORKER"},
    {id: 5, name: "FREE ZONE / FREELANCER"},
    {id: 6, name: "FAMILY VISA"},
    {id: 7, name: "STUDENT VISA"},
    {id: 8, name: "GOLDEN VISA"},
    {id: 9, name: "GREEN VISA"}
];

export const jobDirectory = [
    {id: 1, name: "READY JOB"},
    {id: 2, name: "NEW JOB"},
];

export const languageProficiency = [
    {id: 1, name: 'Good'},
    {id: 2, name: 'Fair'},
    {id: 3, name: 'Poor'}
];
export const permissions = [
    {name: "View Admin", value: "admin.view"},
    {name: "Create Admin", value: "admin.create"},
    {name: "Edit Admin", value: "admin.edit"},
    {name: "Delete Admin", value: "admin.delete"},
    {name: "View Role", value: "role.view"},
    {name: "Create Role", value: "role.create"},
    {name: "Edit Role", value: "role.edit"},
    {name: "Delete Role", value: "role.delete"},
    {name: "View Agency", value: "agency.view"},
    {name: "Create Agency", value: "agency.create"},
    {name: "Edit Agency", value: "agency.edit"},
    {name: "Delete Agency", value: "agency.delete"},
    {name: "View Single Agency", value: "agency.single-view"},
    {name: "Approve Agency", value: "agency.approve"},
    {name: "View Visa", value: "visa.view"},
    {name: "View Single Visa", value: "visa.single-view"},
    {name: "Create Visa", value: "visa.create"},
    {name: "Edit Visa", value: "visa.edit"},
    {name: "Delete Visa", value: "visa.delete"},
    {name: "Add Document to Visa", value: "visa.add.document"},
    {name: "Delete Visa Document", value: "visa.delete.document"},
    {name: "Change Visa Status", value: "visa.status.change"},
    {name: "View Job Demand", value: "job-post.view"},
    {name: "View Job Apply", value: "job-post.single-view"},
    {name: "View Single Job Apply", value: "job-apply.single-view"},
    {name: "Create Job Demand", value: "job-post.create"},
    {name: "Edit Job Demand", value: "job-post.edit"},
    {name: "Delete Job Demand", value: "job-post.delete"},
    {name: "View User", value: "user.view"},
    {name: "Create User", value: "user.create"}
];

export const permissionEnums = {
    VIEW_ADMIN: "admin.view",
    CREATE_ADMIN: "admin.create",
    EDIT_ADMIN: "admin.edit",
    DELETE_ADMIN: "admin.delete",
    VIEW_ROLE: "role.view",
    CREATE_ROLE: "role.create",
    EDIT_ROLE: "role.edit",
    DELETE_ROLE: "role.delete",
    VIEW_AGENCY: "agency.view",
    CREATE_AGENCY: "agency.create",
    EDIT_AGENCY: "agency.edit",
    DELETE_AGENCY: "agency.delete",
    VIEW_SINGLE_AGENCY: "agency.single-view",
    APPROVE_AGENCY: "agency.approve",
    VIEW_VISA: "visa.view",
    VIEW_SINGLE_VISA: "visa.single-view",
    CREATE_VISA: "visa.create",
    EDIT_VISA: "visa.edit",
    DELETE_VISA: "visa.delete",
    ADD_DOCUMENT_TO_VISA: "visa.add.document",
    DELETE_DOCUMENT_VISA: "visa.delete.document",
    CHANGE_VISA_STATUS: "visa.status.change",
    VIEW_JOB_POST: "job-post.view",
    VIEW_SINGLE_JOB_POST: "job-post.single-view",
    VIEW_SINGLE_JOB_APPLY: "job-apply.single-view",
    CREATE_JOB_POST: "job-post.create",
    EDIT_JOB_POST: "job-post.edit",
    DELETE_JOB_POST: "job-post.delete",
    VIEW_USER: "user.view",
    CREATE_USER: "user.create"
};


export const documentTypes = {
    passport: {type: "passport", name: "Passport Page 1"},
    photo: {type: "photo", name: "Photo"},
    deposit: {type: "deposit", name: "Deposit Paper"},
    id: {type: "id", name: "ID Card"},
    residence: {type: "residence", name: "Residence Letter"},
    sponsor: {type: "sponsor", name: "Sponsor Letter"},
    health: {type: "health", name: "Health Insurance"},
    return_ticker: {type: "return_ticker", name: "Return Ticket"},
    bank: {type: "bank", name: "Bank Statement"},
    proof: {type: "proof", name: "Proof of Employment"},
    additional1: {type: "additional1", name: "Additional Document 1"},
    additional2: {type: "additional2", name: "Additional Document 2"}
};
export const VisaApplyTableHeading = ['No', 'Name', 'Passport No', 'Status', 'Apply Date', 'Action']

export const jobApplyDocuments = [
    {name: "Passport Copy", type: "passport-copy", file: null},
    {name: "Visa Copy", type: "visa-copy", file: null},
    {name: "Apply Picture", type: "apply-picture", file: null},
    {name: "National ID", type: "national-id", file: null},
    {name: "Emirates ID", type: "emirates-id", file: null},
    {name: "Change Status", type: "change-status", file: null},
    {name: "Pre Medical Test", type: "pre-medical-test", file: null},
    {name: "Vaccine Certificate", type: "vaccine-certificate", file: null},
    {name: "MOL Paper", type: "mol-paper", file: null},
    {name: "Labor Card", type: "labor-card", file: null},
    {name: "eVisa", type: "e-visa", file: null},
    {name: "Attested Visa", type: "attested-visa", file: null},
    {name: "TTC Certificate", type: "ttc-certificate", file: null},
    {name: "BMET Card", type: "bmet-card", file: null},
    {name: "Ticket", type: "ticket", file: null},
    {name: "Medical UAE", type: "medical-uae", file: null},
    {name: "Stamping Visa", type: "stamping-visa", file: null},
    {name: "Eye Test", type: "eye-test", file: null},
    {name: "Company NOC", type: "company-noc", file: null},
    {name: "License NOC", type: "license-noc", file: null},
    {name: "Driving License", type: "driving-license", file: null},
    {name: "Driving License (UAE)", type: "driving-license-uae", file: null},
    {name: "Certificate (Academic)", type: "certificate-academic", file: null},
    {name: "Certificate 2", type: "certificate-2", file: null},
    {},
    {name: "Trade License | Others", type: "trade-license-others", file: null},
    {name: "Email | UAE Pass | Info", type: "email-uae-pass-info", file: null}
];

export const joDemand = [
    {id: 1, name: "Yes"},
    {id: 2, name: "No"},
];

export const regions = [
    {id: 1, name: "Inside UAE"},
    {id: 2, name: "Outside UAE"},
];

export const shirtSizes = [
    {id: 'S', name: 'S'},
    {id: 'M', name: 'M'},
    {id: 'L', name: 'L'},
    {id: 'XL', name: 'XL'},
    {id: 'XXL', name: 'XXL'}
];

export const postForApply = [
    {id: 1, value: "drivers", name: "Drivers"},
    {id: 2, value: "bike_rider", name: "Bike Rider"},
    {id: 3, value: "cleaner", name: "Cleaner"},
    {id: 4, value: "painter", name: "Painter"},
    {id: 5, value: "design_painter", name: "Design Painter"},
    {id: 6, value: "mason", name: "Mason"},
    {id: 7, value: "mason_helper", name: "Mason Helper"},
    {id: 8, value: "plumber", name: "Plumber"},
    {id: 9, value: "steel_fixer", name: "Steel Fixer"},
    {id: 10, value: "carpenter", name: "Carpenter"},
    {id: 11, value: "finishing_carpenter", name: "Finishing Carpenter"},
    {id: 12, value: "gypsum_worker", name: "Gypsum Worker"},
    {id: 13, value: "gypsum_designer", name: "Gypsum Designer"},
    {id: 14, value: "construction_helper", name: "Construction Helper"},
    {id: 15, value: "general_helper", name: "General Helper"},
    {id: 16, value: "welder", name: "Welder"},
    {id: 17, value: "aluminum_worker", name: "Aluminum Worker"},
    {id: 18, value: "glass_aluminum", name: "Glass & Aluminum"},
    {id: 19, value: "steel_fabrication", name: "Steel Fabrication"},
    {id: 20, value: "general_labour", name: "General Labour"},
    {id: 21, value: "ordinary_labour", name: "Ordinary Labour"},
    {id: 22, value: "loading_unloading", name: "Loading & Unloading"},
    {id: 23, value: "warehouse_worker", name: "Warehouse Worker"},
    {id: 24, value: "delivery_helper", name: "Delivery Helper"},
    {id: 25, value: "garments", name: "Garments"},
    {id: 26, value: "tailor", name: "Tailor"},
    {id: 27, value: "abaya_tailor", name: "Abaya Tailor"},
    {id: 28, value: "curtain_tailor", name: "Curtain Tailor"},
    {id: 29, value: "car_seat_tailor", name: "Car Seat Tailor"},
    {id: 30, value: "restaurant", name: "Restaurant"},
    {id: 31, value: "cafeteria", name: "Cafeteria"},
    {id: 32, value: "laundry", name: "Laundry"},
    {id: 33, value: "car_wash", name: "Car Wash"},
    {id: 34, value: "sign_maker", name: "Sign Maker"},
    {id: 35, value: "sticker_pester", name: "Sticker Pester"},
    {id: 36, value: "wall_matt_pester", name: "Wall Matt Pester"},
    {id: 37, value: "garage", name: "Garage"},
    {id: 38, value: "car_painter", name: "Car Painter"},
    {id: 39, value: "powder_coating", name: "Powder Coating"},
    {id: 40, value: "engineering", name: "Engineering"},
    {id: 41, value: "workshop", name: "Workshop"},
    {id: 42, value: "turning_workshop", name: "Turning Workshop"},
    {id: 43, value: "natur_watchman", name: "Natur (Watchman)"},
    {id: 44, value: "security", name: "Security"},
    {id: 45, value: "beauty_saloon", name: "Beauty Saloon"},
    {id: 46, value: "ladies_barber", name: "Ladies Barber (Hairdresser)"},
    {id: 47, value: "messenger", name: "Messenger"},
    {id: 48, value: "maid", name: "Maid"},
    {id: 49, value: "baby_sitter", name: "Baby Sitter"},
    {id: 50, value: "khaddama", name: "Khaddama"},
    {id: 51, value: "tabbak", name: "Tabbak"},
    {id: 52, value: "juarf", name: "Juarf"},
    {id: 53, value: "agriculture", name: "Agriculture"},
    {id: 54, value: "free_launcher", name: "Free Launcher"},
    {id: 55, value: "investor_visa", name: "Investor Visa"},
    {id: 56, value: "only_visa", name: "Only Visa"},
    {id: 57, value: "management_staff", name: "Management Staff"},
    {id: 58, value: "hr_officer", name: "HR Officer"},
    {id: 59, value: "finance_manager", name: "Finance Manager"},
    {id: 60, value: "sales_manager", name: "Sales Manager"},
    {id: 61, value: "sales_staff", name: "Sales Staff"},
    {id: 62, value: "sales_executive", name: "Sales Executive"},
    {id: 63, value: "sales_supervisor", name: "Sales Supervisor"},
    {id: 64, value: "sales_representative", name: "Sales Representative"},
    {id: 65, value: "site_supervisor", name: "Site Supervisor"},
    {id: 66, value: "marketing_specialist", name: "Marketing Specialist"},
    {id: 67, value: "executive_secretary", name: "Executive Secretary"},
    {id: 68, value: "accountants", name: "Accountants"},
    {id: 69, value: "accounts_clerk", name: "Accounts Clerk"},
    {id: 70, value: "administration_officer", name: "Administration Officer"},
    {id: 71, value: "reservation_officer", name: "Reservation Officer"},
    {id: 72, value: "public_relation_officer", name: "Public Relation Officer"},
    {id: 73, value: "customer_service_representative", name: "Customer Service Representative"},
    {id: 74, value: "call_center_agents", name: "Call Center Agents"},
    {id: 75, value: "administration_clerk", name: "Administration Clerk"},
    {id: 76, value: "customs_clearing_clerk", name: "Customs Clearing Clerk"},
    {id: 77, value: "customs_clearing_agent", name: "Customs Clearing Agent"},
    {id: 78, value: "customs_representative", name: "Customs Representative"},
    {id: 79, value: "cash_desk_clerk", name: "Cash Desk Clerk"},
    {id: 80, value: "clerk_assistant", name: "Clerk Assistant"},
    {id: 81, value: "archive_clerk", name: "Archive Clerk"},
    {id: 82, value: "quantity_surveyor", name: "Quantity Surveyor"},
    {id: 83, value: "computer_operator", name: "Computer Operator"},
];


export const drivingLicenses = [
    {id: 1, name: "Light motor vehicle (Manual)"},
    {id: 2, name: "Light motor vehicle (Auto)"},
    {id: 3, name: "Motorcycle"},
    {id: 4, name: "Heavy truck"},
    {id: 5, name: "Mini bus"},
    {id: 6, name: "Heavy bus"},
    {id: 7, name: "Fork lift"},
    {id: 8, name: "Shovel"},
];

export const religions = [
    {id: 1, name: "Sunni Muslim"},
    {id: 2, name: "Shiite Muslim"},
    {id: 3, name: "Christian"},
    {id: 4, name: "Hindu"},
    {id: 5, name: "Sikh"},
    {id: 6, name: "Buddhist"}
];


export const countriesList = [
  { name: "United Arab Emirates", code: "ae", dialCode: "+971" },
  { name: "Afghanistan", code: "af", dialCode: "+93" },
  { name: "Albania", code: "al", dialCode: "+355" },
  { name: "Algeria", code: "dz", dialCode: "+213" },
  { name: "American Samoa", code: "as", dialCode: "+1684" },
  { name: "Andorra", code: "ad", dialCode: "+376" },
  { name: "Angola", code: "ao", dialCode: "+244" },
  { name: "Anguilla", code: "ai", dialCode: "+1264" },
  { name: "Antarctica", code: "aq", dialCode: "+672" },
  { name: "Antigua and Barbuda", code: "ag", dialCode: "+1268" },
  { name: "Argentina", code: "ar", dialCode: "+54" },
  { name: "Armenia", code: "am", dialCode: "+374" },
  { name: "Aruba", code: "aw", dialCode: "+297" },
  { name: "Australia", code: "au", dialCode: "+61" },
  { name: "Austria", code: "at", dialCode: "+43" },
  { name: "Azerbaijan", code: "az", dialCode: "+994" },
  { name: "Bahamas", code: "bs", dialCode: "+1242" },
  { name: "Bahrain", code: "bh", dialCode: "+973" },
  { name: "Bangladesh", code: "bd", dialCode: "+880" },
  { name: "Barbados", code: "bb", dialCode: "+1246" },
  { name: "Belarus", code: "by", dialCode: "+375" },
  { name: "Belgium", code: "be", dialCode: "+32" },
  { name: "Belize", code: "bz", dialCode: "+501" },
  { name: "Benin", code: "bj", dialCode: "+229" },
  { name: "Bermuda", code: "bm", dialCode: "+1441" },
  { name: "Bhutan", code: "bt", dialCode: "+975" },
  { name: "Bolivia", code: "bo", dialCode: "+591" },
  { name: "Bosnia and Herzegovina", code: "ba", dialCode: "+387" },
  { name: "Botswana", code: "bw", dialCode: "+267" },
  { name: "Brazil", code: "br", dialCode: "+55" },
  { name: "British Indian Ocean Territory", code: "io", dialCode: "+246" },
  { name: "Brunei Darussalam", code: "bn", dialCode: "+673" },
  { name: "Bulgaria", code: "bg", dialCode: "+359" },
  { name: "Burkina Faso", code: "bf", dialCode: "+226" },
  { name: "Burundi", code: "bi", dialCode: "+257" },
  { name: "Cambodia", code: "kh", dialCode: "+855" },
  { name: "Cameroon", code: "cm", dialCode: "+237" },
  { name: "Canada", code: "ca", dialCode: "+1" },
  { name: "Cape Verde", code: "cv", dialCode: "+238" },
  { name: "Cayman Islands", code: "ky", dialCode: "+1345" },
  { name: "Central African Republic", code: "cf", dialCode: "+236" },
  { name: "Chad", code: "td", dialCode: "+235" },
  { name: "Chile", code: "cl", dialCode: "+56" },
  { name: "China", code: "cn", dialCode: "+86" },
  { name: "Christmas Island", code: "cx", dialCode: "+61" },
  { name: "Cocos (Keeling) Islands", code: "cc", dialCode: "+61" },
  { name: "Colombia", code: "co", dialCode: "+57" },
  { name: "Comoros", code: "km", dialCode: "+269" },
  { name: "Congo", code: "cg", dialCode: "+242" },
  { name: "Congo, The Democratic Republic of the", code: "cd", dialCode: "+243" },
  { name: "Cook Islands", code: "ck", dialCode: "+682" },
  { name: "Costa Rica", code: "cr", dialCode: "+506" },
  { name: "Cote d'Ivoire", code: "ci", dialCode: "+225" },
  { name: "Croatia", code: "hr", dialCode: "+385" },
  { name: "Cuba", code: "cu", dialCode: "+53" },
  { name: "Cyprus", code: "cy", dialCode: "+357" },
  { name: "Czech Republic", code: "cz", dialCode: "+420" },
  { name: "Denmark", code: "dk", dialCode: "+45" },
  { name: "Djibouti", code: "dj", dialCode: "+253" },
  { name: "Dominica", code: "dm", dialCode: "+1767" },
  { name: "Dominican Republic", code: "do", dialCode: "+1849" },
  { name: "Ecuador", code: "ec", dialCode: "+593" },
  { name: "Egypt", code: "eg", dialCode: "+20" },
  { name: "El Salvador", code: "sv", dialCode: "+503" },
  { name: "Equatorial Guinea", code: "gq", dialCode: "+240" },
  { name: "Eritrea", code: "er", dialCode: "+291" },
  { name: "Estonia", code: "ee", dialCode: "+372" },
  { name: "Ethiopia", code: "et", dialCode: "+251" },
  { name: "Falkland Islands (Malvinas)", code: "fk", dialCode: "+500" },
  { name: "Faroe Islands", code: "fo", dialCode: "+298" },
  { name: "Fiji", code: "fj", dialCode: "+679" },
  { name: "Finland", code: "fi", dialCode: "+358" },
  { name: "France", code: "fr", dialCode: "+33" },
  { name: "French Guiana", code: "gf", dialCode: "+594" },
  { name: "French Polynesia", code: "pf", dialCode: "+689" },
  { name: "Gabon", code: "ga", dialCode: "+241" },
  { name: "Gambia", code: "gm", dialCode: "+220" },
  { name: "Georgia", code: "ge", dialCode: "+995" },
  { name: "Germany", code: "de", dialCode: "+49" },
  { name: "Ghana", code: "gh", dialCode: "+233" },
  { name: "Gibraltar", code: "gi", dialCode: "+350" },
  { name: "Greece", code: "gr", dialCode: "+30" },
  { name: "Greenland", code: "gl", dialCode: "+299" },
  { name: "Grenada", code: "gd", dialCode: "+1473" },
  { name: "Guadeloupe", code: "gp", dialCode: "+590" },
  { name: "Guam", code: "gu", dialCode: "+1671" },
  { name: "Guatemala", code: "gt", dialCode: "+502" },
  { name: "Guernsey", code: "gg", dialCode: "+44" },
  { name: "Guinea", code: "gn", dialCode: "+224" },
  { name: "Guinea-Bissau", code: "gw", dialCode: "+245" },
  { name: "Guyana", code: "gy", dialCode: "+592" },
  { name: "Haiti", code: "ht", dialCode: "+509" },
  { name: "Holy See (Vatican City State)", code: "va", dialCode: "+379" },
  { name: "Honduras", code: "hn", dialCode: "+504" },
  { name: "Hong Kong", code: "hk", dialCode: "+852" },
  { name: "Hungary", code: "hu", dialCode: "+36" },
  { name: "Iceland", code: "is", dialCode: "+354" },
  { name: "India", code: "in", dialCode: "+91" },
  { name: "Indonesia", code: "id", dialCode: "+62" },
  { name: "Iran, Islamic Republic of", code: "ir", dialCode: "+98" },
  { name: "Iraq", code: "iq", dialCode: "+964" },
  { name: "Ireland", code: "ie", dialCode: "+353" },
  { name: "Isle of Man", code: "im", dialCode: "+44" },
  { name: "Israel", code: "il", dialCode: "+972" },
  { name: "Italy", code: "it", dialCode: "+39" },
  { name: "Jamaica", code: "jm", dialCode: "+1876" },
  { name: "Japan", code: "jp", dialCode: "+81" },
  { name: "Jersey", code: "je", dialCode: "+44" },
  { name: "Jordan", code: "jo", dialCode: "+962" },
  { name: "Kazakhstan", code: "kz", dialCode: "+7" },
  { name: "Kenya", code: "ke", dialCode: "+254" },
  { name: "Kiribati", code: "ki", dialCode: "+686" },
  { name: "Korea, Democratic People's Republic of", code: "kp", dialCode: "+850" },
  { name: "Korea, Republic of", code: "kr", dialCode: "+82" },
  { name: "Kuwait", code: "kw", dialCode: "+965" },
  { name: "Kyrgyzstan", code: "kg", dialCode: "+996" },
  { name: "Lao People's Democratic Republic", code: "la", dialCode: "+856" },
  { name: "Latvia", code: "lv", dialCode: "+371" },
  { name: "Lebanon", code: "lb", dialCode: "+961" },
  { name: "Lesotho", code: "ls", dialCode: "+266" },
  { name: "Liberia", code: "lr", dialCode: "+231" },
  { name: "Libyan Arab Jamahiriya", code: "ly", dialCode: "+218" },
  { name: "Liechtenstein", code: "li", dialCode: "+423" },
  { name: "Lithuania", code: "lt", dialCode: "+370" },
  { name: "Luxembourg", code: "lu", dialCode: "+352" },
  { name: "Macao", code: "mo", dialCode: "+853" },
  { name: "Macedonia", code: "mk", dialCode: "+389" },
  { name: "Madagascar", code: "mg", dialCode: "+261" },
  { name: "Malawi", code: "mw", dialCode: "+265" },
  { name: "Malaysia", code: "my", dialCode: "+60" },
  { name: "Maldives", code: "mv", dialCode: "+960" },
  { name: "Mali", code: "ml", dialCode: "+223" },
  { name: "Malta", code: "mt", dialCode: "+356" },
  { name: "Marshall Islands", code: "mh", dialCode: "+692" },
  { name: "Martinique", code: "mq", dialCode: "+596" },
  { name: "Mauritania", code: "mr", dialCode: "+222" },
  { name: "Mauritius", code: "mu", dialCode: "+230" },
  { name: "Mayotte", code: "yt", dialCode: "+262" },
  { name: "Mexico", code: "mx", dialCode: "+52" },
  { name: "Micronesia, Federated States of", code: "fm", dialCode: "+691" },
  { name: "Moldova, Republic of", code: "md", dialCode: "+373" },
  { name: "Monaco", code: "mc", dialCode: "+377" },
  { name: "Mongolia", code: "mn", dialCode: "+976" },
  { name: "Montenegro", code: "me", dialCode: "+382" },
  { name: "Montserrat", code: "ms", dialCode: "+1664" },
  { name: "Morocco", code: "ma", dialCode: "+212" },
  { name: "Mozambique", code: "mz", dialCode: "+258" },
  { name: "Myanmar", code: "mm", dialCode: "+95" },
  { name: "Namibia", code: "na", dialCode: "+264" },
  { name: "Nauru", code: "nr", dialCode: "+674" },
  { name: "Nepal", code: "np", dialCode: "+977" },
  { name: "Netherlands", code: "nl", dialCode: "+31" },
  { name: "Netherlands Antilles", code: "an", dialCode: "+599" },
  { name: "New Caledonia", code: "nc", dialCode: "+687" },
  { name: "New Zealand", code: "nz", dialCode: "+64" },
  { name: "Nicaragua", code: "ni", dialCode: "+505" },
  { name: "Niger", code: "ne", dialCode: "+227" },
  { name: "Nigeria", code: "ng", dialCode: "+234" },
  { name: "Niue", code: "nu", dialCode: "+683" },
  { name: "Norfolk Island", code: "nf", dialCode: "+672" },
  { name: "Northern Mariana Islands", code: "mp", dialCode: "+1670" },
  { name: "Norway", code: "no", dialCode: "+47" },
  { name: "Oman", code: "om", dialCode: "+968" },
  { name: "Pakistan", code: "pk", dialCode: "+92" },
  { name: "Palau", code: "pw", dialCode: "+680" },
  { name: "Palestinian Territory, Occupied", code: "ps", dialCode: "+970" },
  { name: "Panama", code: "pa", dialCode: "+507" },
  { name: "Papua New Guinea", code: "pg", dialCode: "+675" },
  { name: "Paraguay", code: "py", dialCode: "+595" },
  { name: "Peru", code: "pe", dialCode: "+51" },
  { name: "Philippines", code: "ph", dialCode: "+63" },
  { name: "Pitcairn", code: "pn", dialCode: "+64" },
  { name: "Poland", code: "pl", dialCode: "+48" },
  { name: "Portugal", code: "pt", dialCode: "+351" },
  { name: "Puerto Rico", code: "pr", dialCode: "+1939" },
  { name: "Qatar", code: "qa", dialCode: "+974" },
  { name: "Reunion", code: "re", dialCode: "+262" },
  { name: "Romania", code: "ro", dialCode: "+40" },
  { name: "Russian Federation", code: "ru", dialCode: "+7" },
  { name: "Rwanda", code: "rw", dialCode: "+250" },
  { name: "Saint Kitts and Nevis", code: "kn", dialCode: "+1869" },
  { name: "Saint Lucia", code: "lc", dialCode: "+1758" },
  { name: "Saint Pierre and Miquelon", code: "pm", dialCode: "+508" },
  { name: "Saint Vincent and the Grenadines", code: "vc", dialCode: "+1784" },
  { name: "Samoa", code: "ws", dialCode: "+685" },
  { name: "San Marino", code: "sm", dialCode: "+378" },
  { name: "Sao Tome and Principe", code: "st", dialCode: "+239" },
  { name: "Saudi Arabia", code: "sa", dialCode: "+966" },
  { name: "Senegal", code: "sn", dialCode: "+221" },
  { name: "Serbia", code: "rs", dialCode: "+381" },
  { name: "Seychelles", code: "sc", dialCode: "+248" },
  { name: "Sierra Leone", code: "sl", dialCode: "+232" },
  { name: "Singapore", code: "sg", dialCode: "+65" },
  { name: "Slovakia", code: "sk", dialCode: "+421" },
  { name: "Slovenia", code: "si", dialCode: "+386" },
  { name: "Solomon Islands", code: "sb", dialCode: "+677" },
  { name: "Somalia", code: "so", dialCode: "+252" },
  { name: "South Africa", code: "za", dialCode: "+27" },
  { name: "South Sudan", code: "ss", dialCode: "+211" },
  { name: "Spain", code: "es", dialCode: "+34" },
  { name: "Sri Lanka", code: "lk", dialCode: "+94" },
  { name: "Sudan", code: "sd", dialCode: "+249" },
  { name: "Suriname", code: "sr", dialCode: "+597" },
  { name: "Svalbard and Jan Mayen", code: "sj", dialCode: "+47" },
  { name: "Swaziland", code: "sz", dialCode: "+268" },
  { name: "Sweden", code: "se", dialCode: "+46" },
  { name: "Switzerland", code: "ch", dialCode: "+41" },
  { name: "Syrian Arab Republic", code: "sy", dialCode: "+963" },
  { name: "Taiwan", code: "tw", dialCode: "+886" },
  { name: "Tajikistan", code: "tj", dialCode: "+992" },
  { name: "Tanzania, United Republic of", code: "tz", dialCode: "+255" },
  { name: "Thailand", code: "th", dialCode: "+66" },
  { name: "Timor-Leste", code: "tl", dialCode: "+670" },
  { name: "Togo", code: "tg", dialCode: "+228" },
  { name: "Tokelau", code: "tk", dialCode: "+690" },
  { name: "Tonga", code: "to", dialCode: "+676" },
  { name: "Trinidad and Tobago", code: "tt", dialCode: "+1868" },
  { name: "Tunisia", code: "tn", dialCode: "+216" },
  { name: "Turkey", code: "tr", dialCode: "+90" },
  { name: "Turkmenistan", code: "tm", dialCode: "+993" },
  { name: "Turks and Caicos Islands", code: "tc", dialCode: "+1649" },
  { name: "Tuvalu", code: "tv", dialCode: "+688" },
  { name: "Uganda", code: "ug", dialCode: "+256" },
  { name: "Ukraine", code: "ua", dialCode: "+380" },
  { name: "United Kingdom", code: "gb", dialCode: "+44" },
  { name: "United States", code: "us", dialCode: "+1" },
  { name: "Uruguay", code: "uy", dialCode: "+598" },
  { name: "Uzbekistan", code: "uz", dialCode: "+998" },
  { name: "Vanuatu", code: "vu", dialCode: "+678" },
  { name: "Venezuela", code: "ve", dialCode: "+58" },
  { name: "Vietnam", code: "vn", dialCode: "+84" },
  { name: "Virgin Islands, British", code: "vg", dialCode: "+1284" },
  { name: "Virgin Islands, U.S.", code: "vi", dialCode: "+1340" },
  { name: "Wallis and Futuna", code: "wf", dialCode: "+681" },
  { name: "Western Sahara", code: "eh", dialCode: "+212" },
  { name: "Yemen", code: "ye", dialCode: "+967" },
  { name: "Zambia", code: "zm", dialCode: "+260" },
  { name: "Zimbabwe", code: "zw", dialCode: "+263" }
];
