services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: evisa_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - uploads_volume:/var/www/public/uploads
        networks:
            - laravel_network
        depends_on:
            - nginx
            - mysql
        environment:
            - APP_NAME=DubaiEvisa
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=evisa
            - DB_USERNAME=root
            - DB_PASSWORD=e2nIg2IH27pi7FEoZ0
            - APP_URL=https://dubaievisaservice.com
            - SESSION_DRIVER=database
            - CACHE_STORE=database
            - QUEUE_CONNECTION=database
            - MAIL_MAILER=log
            - MAIL_HOST=smtp.mailtrap.io
            - MAIL_PORT=2525
            - MAIL_USERNAME=null
            - MAIL_PASSWORD=null
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"
            - OCTANE_SERVER=swoole
        command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000

    nginx:
        image: nginx:latest
        container_name: evisa_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network

    mysql:
        image: mysql:latest
        container_name: evisa_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: e2nIg2IH27pi7FEoZ0
            MYSQL_DATABASE: evisa
            MYSQL_USER: root
            MYSQL_PASSWORD: e2nIg2IH27pi7FEoZ0
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    uploads_volume:
    mysql_data:
