version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: evisa
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - uploads_volume:/var/www/public/uploads # Persist uploads
        networks:
            - laravel_network
        depends_on:
            - nginx
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=your_mysql_host # MySQL is outside of Docker

    nginx:
        image: nginx:latest
        container_name: evisa_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network

    node:
        image: node:20
        container_name: evisa_node
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        command: [ "sh", "-c", "npm install && npm run dev" ]

networks:
    laravel_network:
        driver: bridge

volumes:
    uploads_volume: # Named volume for persisting uploads
